version: 2

aliases: &build
  environment:
    BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"

  machine: true

  parallelism: 2

  steps:
    - checkout

    - run:
        name: install nixpkgs
        command: curl https://nixos.org/nix/install | sh

    # Restore /nix to state after running the tests that depends only on
    # release.nix, which is the file to change if the version nixpkgs that is
    # pinned ever changes (cf https://circleci.com/docs/2.0/caching/)

    - restore_cache:
        keys:
          - nix-cache-v1-{{ arch }}-{{ checksum "release.nix" }}

    - run:
        name: install test dependencies
        command: ./fixtures/install_test_deps.sh

    - run:
        name: run the tests
        command: ./test.sh

    # Save /nix to the cache.

    - save_cache:
        key: nix-cache-v1-{{ arch }}-{{ checksum "release.nix" }}
        paths:
          - /nix

jobs:
  build: *build
