version: 2

aliases: &build
  environment:
    BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"

  machine: true

  parallelism: 2

  steps:
    - checkout

    - run:
        name: create a fake /nix
        command: sudo mkdir -m 0755 /nix && sudo chown circleci /nix

    # Restore the nix installation to state after running the tests
    # - restore_cache:
    #     keys:
    #       - nix-root-v1-{{ arch }}-{{ checksum "release.nix" }}

    - restore_cache:
        keys:
          - nix-dotnix-v1-{{ arch }}-{{ checksum "release.nix" }}

    - run:
        name: install nix
        command: ./fixtures/install_nix.sh

    - run:
        name: install test dependencies
        command: ./fixtures/install_test_deps.sh

    - run:
        name: run the tests
        command: ./test.sh

    # Save /nix and the local folders to the cache.

    - save_cache:
        key: nix-root-v1-{{ arch }}-{{ checksum "release.nix" }}
        paths:
          - /nix

    - save_cache:
        key: nix-dotnix-v1-{{ arch }}-{{ checksum "release.nix" }}
        paths:
          - ~/.nix-profile
          - ~/.nix-defexpr

jobs:
  build: *build
